### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by pinvisible** [apl-devs/AppIntro#398]
# My Code: 
addSlide(new IntroductionScreen());
addSlide(new IntroductionScreen());

---------------------------------------------------------------------------------------------
# Error : 
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                       at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
                                                                       at java.util.Vector.elementAt(Vector.java:328)
                                                                       at java.util.Vector.get(Vector.java:442)
                                                                       at com.github.paolorotolo.appintro.PagerAdapter.getItem(PagerAdapter.java:32)
                                                                       at com.github.paolorotolo.appintro.AppIntroBase$4.run(AppIntroBase.java:151)
                                                                       at android.os.Handler.handleCallback(Handler.java:746)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by avluis** [comment]
I'm sorry, but we can't read minds just yet -- can you post your `IntroductionScreen()` method along with the rest of your code?

**Comment by pinvisible** [comment]
Yes, of course. It is simply a fragment. 

public class IntroductionScreen extends Fragment {
    // TODO: Rename parameter arguments, choose names that match

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_splash_screen, container, false);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
    }
}

**Comment by pinvisible** [comment]
Hello There.

i got solution.. 

I was using another onCreate method, so it was giving error.

public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState) {
        super.onCreate(savedInstanceState, persistentState);
