### ISSUE TITLE
android.view.InflateException: Binary XML file line #28: Error inflating class TextView, java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6

### ISSUE THREAD

**Issue by VallaDanger** [apl-devs/AppIntro#450]
**AppIntro Version**: 4.2.0

**Device/Android Version**: XT1064/6.0

**Issue details / Repro steps / Use case background**:  simplest case scenario, adding just one slide
the problems points to: **AppIntro/library/src/main/res/layout/intro_layout2.xml**

<TextView
            android:id="@+id/bottom_separator"
            android:layout_width="fill_parent"
            android:layout_height="1px"
            android:background="#55000000"
            android:visibility="gone" />

**com.android.support**: 25.4.0

**Your Code**: 

import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.Nullable;

import com.github.paolorotolo.appintro.AppIntro2;
import com.github.paolorotolo.appintro.AppIntro2Fragment;

public class ActivityIntro extends AppIntro2 {
  @Override
  public void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    addSlide(AppIntro2Fragment.newInstance("test", "test", R.drawable.test,
        Color.parseColor("#3F51B5"), Color.parseColor("#3F51B5"), Color.parseColor("#3F51B5")));
  }
}

**Stack trace / LogCat**:
```
Caused by: android.view.InflateException: Binary XML file line #28: Binary XML file line #28: Error inflating class TextView
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                  at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:80)
                                                                                  at com.github.paolorotolo.appintro.AppIntro2.onCreate(AppIntro2.java:24)
                                                                                  at com.test.main.activities.intro.ActivityIntro.onCreate(ActivityIntro.java:23) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6245)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                               Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class TextView
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                  at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:80) 
                                                                                  at com.github.paolorotolo.appintro.AppIntro2.onCreate(AppIntro2.java:24) 
                                                                                  at com.test.main.activities.intro.ActivityIntro.onCreate(ActivityIntro.java:23) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6245) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                               Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
                                                                                  at android.content.res.TypedArray.getColorStateList(TypedArray.java:482)
                                                                                  at android.widget.TextView.<init>(TextView.java:750)
                                                                                  at android.widget.TextView.<init>(TextView.java:671)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                                  at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                                  at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                  at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:80) 
                                                                                  at com.github.paolorotolo.appintro.AppIntro2.onCreate(AppIntro2.java:24) 
                                                                                  at com.test.main.activities.intro.ActivityIntro.onCreate(ActivityIntro.java:23) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6245) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by avluis** [comment]
@VallaDanger
Can you try changing `extends AppIntro2` to `extends AppIntro` -- report results, of course 🐱

**Comment by VallaDanger** [comment]
@avluis 
Thank you for your quick response. I've found out that the value of the `colorAccent` property was not properly set and the library is highly sensitive to that particular value.

**Comment by avluis** [comment]
@VallaDanger Thanks for the head up~

**Comment by himanshu366** [comment]
Try using the resource folder to access the file containing the respective data.
