### ISSUE TITLE
NPE when no slides have been defined

### ISSUE THREAD

**Issue by Kirkan** [apl-devs/AppIntro#455]
Problem on releases after 3.3.0
```
Intent intro = new Intent(this, Intro.class);
startActivity(intro);
....
public class Intro extends AppIntro {
    private SharedPreferences app_preferences;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        app_preferences = PreferenceManager.getDefaultSharedPreferences(this);
        if (false) {
            addSlide(IntroFragment.newInstance(R.layout.intro1));
        }
        if (false) {
            addSlide(Intro2Fragment.newInstance(R.layout.intro2));
        }
        showSkipButton(false);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        this.finish();
    }
}
```
This code throw:
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
	at java.util.Vector.elementAt(Vector.java:328)
	at java.util.Vector.get(Vector.java:442)
	at com.github.paolorotolo.appintro.PagerAdapter.getItem(PagerAdapter.java:32)
	at com.github.paolorotolo.appintro.AppIntroBase$4.run(AppIntroBase.java:192)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
I think you need add not null check in PagerAdapter.getItem(PagerAdapter.java:32)
Thanks!

**Comment by avluis** [comment]
Go ahead and create a PR if you want this specific use case to be covered -- though you are using the library out of scope.
