### ISSUE TITLE
[Crash] if image size 2MB it'll be crash

### ISSUE THREAD

**Issue by chihung93** [apl-devs/AppIntro#465]
Zenfone 3
Ram : 3GB
Android : 6.0

You should use Glide for image large .

```
07-19 17:04:59.655 12281-12281/com.amqtech.opensource.appintroexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.amqtech.opensource.appintroexample, PID: 12281
                                                                                        java.lang.OutOfMemoryError: Failed to allocate a 216000012 byte allocation with 16777216 free bytes and 165MB until OOM
                                                                                            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                                            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
                                                                                            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
                                                                                            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
                                                                                            at android.content.res.Resources.loadDrawableForCookie(Resources.java:2658)
                                                                                            at android.content.res.Resources.loadDrawable(Resources.java:2563)
                                                                                            at android.content.res.Resources.getDrawable(Resources.java:821)
                                                                                            at android.content.Context.getDrawable(Context.java:458)
                                                                                            at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
                                                                                            at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                                            at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                                            at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
                                                                                            at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
                                                                                            at com.github.paolorotolo.appintro.AppIntroBaseFragment.onCreateView(AppIntroBaseFragment.java:103)
                                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                            at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                                            at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                                            at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                            at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                                            at android.view.View.measure(View.java:18805)
                                                                                            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                                            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                                            at android.view.View.measure(View.java:18805)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                            at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                            at android.view.View.measure(View.java:18805)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                            at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                            at android.view.View.measure(View.java:18805)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                            at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                            at android.view.View.measure(View.java:18805)
                                                                                            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                            at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                        	at android.widg
```

**Comment by avluis** [comment]
Yes...
You should be using an image loading library if you are going to be loading images of this size...
